# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _TCWordSeg
else:
    import _TCWordSeg

try:
    import builtins as __builtin__
except ImportError:
    # import __builtin__
    pass

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class token_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    word = property(_TCWordSeg.token_t_word_get, _TCWordSeg.token_t_word_set)
    pos = property(_TCWordSeg.token_t_pos_get, _TCWordSeg.token_t_pos_set)
    wlen = property(_TCWordSeg.token_t_wlen_get, _TCWordSeg.token_t_wlen_set)
    wtype = property(_TCWordSeg.token_t_wtype_get, _TCWordSeg.token_t_wtype_set)

    def __init__(self):
        _TCWordSeg.token_t_swiginit(self, _TCWordSeg.new_token_t())
    __swig_destroy__ = _TCWordSeg.delete_token_t

# Register token_t in _TCWordSeg:
_TCWordSeg.token_t_swigregister(token_t)

class comb_token_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    word = property(_TCWordSeg.comb_token_t_word_get, _TCWordSeg.comb_token_t_word_set)
    pos = property(_TCWordSeg.comb_token_t_pos_get, _TCWordSeg.comb_token_t_pos_set)
    wlen = property(_TCWordSeg.comb_token_t_wlen_get, _TCWordSeg.comb_token_t_wlen_set)
    cls = property(_TCWordSeg.comb_token_t_cls_get, _TCWordSeg.comb_token_t_cls_set)
    sidx = property(_TCWordSeg.comb_token_t_sidx_get, _TCWordSeg.comb_token_t_sidx_set)
    eidx = property(_TCWordSeg.comb_token_t_eidx_get, _TCWordSeg.comb_token_t_eidx_set)

    def __init__(self):
        _TCWordSeg.comb_token_t_swiginit(self, _TCWordSeg.new_comb_token_t())
    __swig_destroy__ = _TCWordSeg.delete_comb_token_t

# Register comb_token_t in _TCWordSeg:
_TCWordSeg.comb_token_t_swigregister(comb_token_t)

class seg_tokens_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    fine_grain_seg_tokens = property(_TCWordSeg.seg_tokens_t_fine_grain_seg_tokens_get, _TCWordSeg.seg_tokens_t_fine_grain_seg_tokens_set)
    fine_grain_tokens_num = property(_TCWordSeg.seg_tokens_t_fine_grain_tokens_num_get, _TCWordSeg.seg_tokens_t_fine_grain_tokens_num_set)
    thick_seg_tokens = property(_TCWordSeg.seg_tokens_t_thick_seg_tokens_get, _TCWordSeg.seg_tokens_t_thick_seg_tokens_set)
    thick_seg_tokens_num = property(_TCWordSeg.seg_tokens_t_thick_seg_tokens_num_get, _TCWordSeg.seg_tokens_t_thick_seg_tokens_num_set)
    custom_defined_tokens = property(_TCWordSeg.seg_tokens_t_custom_defined_tokens_get, _TCWordSeg.seg_tokens_t_custom_defined_tokens_set)
    custom_tokens_num = property(_TCWordSeg.seg_tokens_t_custom_tokens_num_get, _TCWordSeg.seg_tokens_t_custom_tokens_num_set)
    custom_defined_phrases = property(_TCWordSeg.seg_tokens_t_custom_defined_phrases_get, _TCWordSeg.seg_tokens_t_custom_defined_phrases_set)
    custom_phrases_num = property(_TCWordSeg.seg_tokens_t_custom_phrases_num_get, _TCWordSeg.seg_tokens_t_custom_phrases_num_set)
    synonym_tokens = property(_TCWordSeg.seg_tokens_t_synonym_tokens_get, _TCWordSeg.seg_tokens_t_synonym_tokens_set)
    synonym_tokens_num = property(_TCWordSeg.seg_tokens_t_synonym_tokens_num_get, _TCWordSeg.seg_tokens_t_synonym_tokens_num_set)

    def __init__(self):
        _TCWordSeg.seg_tokens_t_swiginit(self, _TCWordSeg.new_seg_tokens_t())
    __swig_destroy__ = _TCWordSeg.delete_seg_tokens_t

# Register seg_tokens_t in _TCWordSeg:
_TCWordSeg.seg_tokens_t_swigregister(seg_tokens_t)

class WP(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    word = property(_TCWordSeg.WP_word_get, _TCWordSeg.WP_word_set)
    pos = property(_TCWordSeg.WP_pos_get, _TCWordSeg.WP_pos_set)
    bcw = property(_TCWordSeg.WP_bcw_get, _TCWordSeg.WP_bcw_set)
    cls = property(_TCWordSeg.WP_cls_get, _TCWordSeg.WP_cls_set)

    def __init__(self):
        _TCWordSeg.WP_swiginit(self, _TCWordSeg.new_WP())
    __swig_destroy__ = _TCWordSeg.delete_WP

# Register WP in _TCWordSeg:
_TCWordSeg.WP_swigregister(WP)

class ms_word_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    word = property(_TCWordSeg.ms_word_t_word_get, _TCWordSeg.ms_word_t_word_set)
    idx = property(_TCWordSeg.ms_word_t_idx_get, _TCWordSeg.ms_word_t_idx_set)

    def __init__(self):
        _TCWordSeg.ms_word_t_swiginit(self, _TCWordSeg.new_ms_word_t())
    __swig_destroy__ = _TCWordSeg.delete_ms_word_t

# Register ms_word_t in _TCWordSeg:
_TCWordSeg.ms_word_t_swigregister(ms_word_t)

class ms_wp_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    word = property(_TCWordSeg.ms_wp_t_word_get, _TCWordSeg.ms_wp_t_word_set)
    pos = property(_TCWordSeg.ms_wp_t_pos_get, _TCWordSeg.ms_wp_t_pos_set)
    bcw = property(_TCWordSeg.ms_wp_t_bcw_get, _TCWordSeg.ms_wp_t_bcw_set)
    cls = property(_TCWordSeg.ms_wp_t_cls_get, _TCWordSeg.ms_wp_t_cls_set)
    idx = property(_TCWordSeg.ms_wp_t_idx_get, _TCWordSeg.ms_wp_t_idx_set)

    def __init__(self):
        _TCWordSeg.ms_wp_t_swiginit(self, _TCWordSeg.new_ms_wp_t())
    __swig_destroy__ = _TCWordSeg.delete_ms_wp_t

# Register ms_wp_t in _TCWordSeg:
_TCWordSeg.ms_wp_t_swigregister(ms_wp_t)

OUT_WORD = _TCWordSeg.OUT_WORD
OUT_PHRASE = _TCWordSeg.OUT_PHRASE
OUT_SUBPHRASE = _TCWordSeg.OUT_SUBPHRASE
TC_ENGU = _TCWordSeg.TC_ENGU
TC_GU = _TCWordSeg.TC_GU
TC_POS = _TCWordSeg.TC_POS
TC_USR = _TCWordSeg.TC_USR
TC_S2D = _TCWordSeg.TC_S2D
TC_U2L = _TCWordSeg.TC_U2L
TC_CLS = _TCWordSeg.TC_CLS
TC_RUL = _TCWordSeg.TC_RUL
TC_CN = _TCWordSeg.TC_CN
TC_T2S = _TCWordSeg.TC_T2S
TC_PGU = _TCWordSeg.TC_PGU
TC_LGU = _TCWordSeg.TC_LGU
TC_SGU = _TCWordSeg.TC_SGU
TC_CUT = _TCWordSeg.TC_CUT
TC_TEXT = _TCWordSeg.TC_TEXT
TC_CONV = _TCWordSeg.TC_CONV
TC_WMUL = _TCWordSeg.TC_WMUL
TC_PMUL = _TCWordSeg.TC_PMUL
TC_ASC = _TCWordSeg.TC_ASC
TC_SECPOS = _TCWordSeg.TC_SECPOS
TC_GBK = _TCWordSeg.TC_GBK
TC_UTF8 = _TCWordSeg.TC_UTF8
TC_NEW_RES = _TCWordSeg.TC_NEW_RES
TC_SYN = _TCWordSeg.TC_SYN
TC_LN = _TCWordSeg.TC_LN
TC_WGU = _TCWordSeg.TC_WGU
TC_A = _TCWordSeg.TC_A
TC_AD = _TCWordSeg.TC_AD
TC_AN = _TCWordSeg.TC_AN
TC_B = _TCWordSeg.TC_B
TC_C = _TCWordSeg.TC_C
TC_D = _TCWordSeg.TC_D
TC_E = _TCWordSeg.TC_E
TC_F = _TCWordSeg.TC_F
TC_G = _TCWordSeg.TC_G
TC_H = _TCWordSeg.TC_H
TC_I = _TCWordSeg.TC_I
TC_J = _TCWordSeg.TC_J
TC_K = _TCWordSeg.TC_K
TC_L = _TCWordSeg.TC_L
TC_M = _TCWordSeg.TC_M
TC_N = _TCWordSeg.TC_N
TC_NR = _TCWordSeg.TC_NR
TC_NRF = _TCWordSeg.TC_NRF
TC_NRG = _TCWordSeg.TC_NRG
TC_NS = _TCWordSeg.TC_NS
TC_NT = _TCWordSeg.TC_NT
TC_NZ = _TCWordSeg.TC_NZ
TC_NX = _TCWordSeg.TC_NX
TC_O = _TCWordSeg.TC_O
TC_P = _TCWordSeg.TC_P
TC_Q = _TCWordSeg.TC_Q
TC_R = _TCWordSeg.TC_R
TC_S = _TCWordSeg.TC_S
TC_T = _TCWordSeg.TC_T
TC_U = _TCWordSeg.TC_U
TC_V = _TCWordSeg.TC_V
TC_VD = _TCWordSeg.TC_VD
TC_VN = _TCWordSeg.TC_VN
TC_W = _TCWordSeg.TC_W
TC_X = _TCWordSeg.TC_X
TC_Y = _TCWordSeg.TC_Y
TC_Z = _TCWordSeg.TC_Z
TC_AG = _TCWordSeg.TC_AG
TC_BG = _TCWordSeg.TC_BG
TC_DG = _TCWordSeg.TC_DG
TC_MG = _TCWordSeg.TC_MG
TC_NG = _TCWordSeg.TC_NG
TC_QG = _TCWordSeg.TC_QG
TC_RG = _TCWordSeg.TC_RG
TC_TG = _TCWordSeg.TC_TG
TC_VG = _TCWordSeg.TC_VG
TC_YG = _TCWordSeg.TC_YG
TC_ZG = _TCWordSeg.TC_ZG
TC_SOS = _TCWordSeg.TC_SOS
TC_EOS = _TCWordSeg.TC_EOS
TC_UNK = _TCWordSeg.TC_UNK
TC_WWW = _TCWordSeg.TC_WWW
TC_TELE = _TCWordSeg.TC_TELE
TC_EMAIL = _TCWordSeg.TC_EMAIL

def TCInitSeg(lpszDataDirPath):
    return _TCWordSeg.TCInitSeg(lpszDataDirPath)

def TCCreateSegHandle(iResultMode):
    return _TCWordSeg.TCCreateSegHandle(iResultMode)

def TCSegment(hHandle, lpText, nTextLen=0, nCharSet=0x00100000):
    return _TCWordSeg.TCSegment(hHandle, lpText, nTextLen, nCharSet)

def TCGetResultCnt(hHandle):
    return _TCWordSeg.TCGetResultCnt(hHandle)

def TCGetWordAt(hHandle, index):
    return _TCWordSeg.TCGetWordAt(hHandle, index)

def TCGetAt(hHandle, index):
    return _TCWordSeg.TCGetAt(hHandle, index)

def TCMSGetWordAt(hHandle, index):
    return _TCWordSeg.TCMSGetWordAt(hHandle, index)

def TCMSGetAt(hHandle, index):
    return _TCWordSeg.TCMSGetAt(hHandle, index)

def TCGetAllSegInfo(hHandle, seg_tokens):
    return _TCWordSeg.TCGetAllSegInfo(hHandle, seg_tokens)

def TCConvertWordCharsetToUTF8(hHandle, word, wlen):
    return _TCWordSeg.TCConvertWordCharsetToUTF8(hHandle, word, wlen)

def TCCloseSegHandle(hHandle):
    return _TCWordSeg.TCCloseSegHandle(hHandle)

def TCUnInitSeg():
    return _TCWordSeg.TCUnInitSeg()

def TCGetClsNum(hHandle, cls):
    return _TCWordSeg.TCGetClsNum(hHandle, cls)

def TCGetClsAt(hHandle, cls, idx):
    return _TCWordSeg.TCGetClsAt(hHandle, cls, idx)

def TCSetOutMode(hHandle, outMode):
    return _TCWordSeg.TCSetOutMode(hHandle, outMode)

def TCChangeUserDict(sUserDict):
    return _TCWordSeg.TCChangeUserDict(sUserDict)

def TCPosId2Str(idPos, strPos, nBufsize):
    return _TCWordSeg.TCPosId2Str(idPos, strPos, nBufsize)

def TCSetPKUMode(hHandle):
    return _TCWordSeg.TCSetPKUMode(hHandle)


